language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
  matrix:
    - PLONE_VERSION=4.3
    - PLONE_VERSION=5.0
    - PLONE_VERSION=5.1
install:
  - sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
  - pip install -r requirements.txt
  - buildout annotate
  - buildout
script:
  - bin/createcoverage -d htmlcov
after_success:
  - pip install coveralls
  - coveralls
